# Generated by Django 5.1.1 on 2024-09-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platmodel',
            name='summary',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
